### ISSUE TITLE
Support Heroku-18 stack

### ISSUE THREAD

**Issue by scottswezey** [HashNuke/heroku-buildpack-elixir-otp-builds#62]
Will support for Heroku's 18 stack be added soon? Would you be interested in a pull request to add support for it?

https://devcenter.heroku.com/articles/heroku-18-stack
https://github.com/heroku/stack-images

**Comment by victorolinasc** [comment]
This is sorely needed for more recent OpenSSL versions.

**Comment by jesseshieh** [comment]
A pull request would definitely be welcome!

**Comment by szymon-jez** [comment]
I have found this PR
https://github.com/HashNuke/heroku-buildpack-elixir-otp-builds/pull/21 which – and reading the current code – tells me that currently the build is done not even on `heroku-16` but still on `cedar-14`, right?

This shows that the builds done on `cedar-14` are working on `heroku-16` and – from my own experience – even on `heroku-18`.

Though I'm still not sure if this is optimal; what benefits would bring building for a specific stack on a matching stack?

BTW `heroku-18` is now the default stack, and so I think that doing builds only on it could make the most sense.
